/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVerifyLauncherPasswordRouteImport } from './routes/api/public/verify-launcher-password'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicBumpVersionRouteImport } from './routes/api/public/bump-version'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyLauncherPasswordRoute =
  ApiPublicVerifyLauncherPasswordRouteImport.update({
    id: '/api/public/verify-launcher-password',
    path: '/api/public/verify-launcher-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBumpVersionRoute = ApiPublicBumpVersionRouteImport.update({
  id: '/api/public/bump-version',
  path: '/api/public/bump-version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/bump-version': typeof ApiPublicBumpVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/verify-launcher-password': typeof ApiPublicVerifyLauncherPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/bump-version': typeof ApiPublicBumpVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/verify-launcher-password': typeof ApiPublicVerifyLauncherPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/public/bump-version': typeof ApiPublicBumpVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/verify-launcher-password': typeof ApiPublicVerifyLauncherPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/bump-version'
    | '/api/public/catalog'
    | '/api/public/verify-launcher-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/bump-version'
    | '/api/public/catalog'
    | '/api/public/verify-launcher-password'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/api/public/bump-version'
    | '/api/public/catalog'
    | '/api/public/verify-launcher-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ApiPublicBumpVersionRoute: typeof ApiPublicBumpVersionRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicVerifyLauncherPasswordRoute: typeof ApiPublicVerifyLauncherPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-launcher-password': {
      id: '/api/public/verify-launcher-password'
      path: '/api/public/verify-launcher-password'
      fullPath: '/api/public/verify-launcher-password'
      preLoaderRoute: typeof ApiPublicVerifyLauncherPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bump-version': {
      id: '/api/public/bump-version'
      path: '/api/public/bump-version'
      fullPath: '/api/public/bump-version'
      preLoaderRoute: typeof ApiPublicBumpVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ApiPublicBumpVersionRoute: ApiPublicBumpVersionRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicVerifyLauncherPasswordRoute: ApiPublicVerifyLauncherPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
