/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LauncherAdminRouteImport } from './routes/launcher-admin'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LauncherAdminIndexRouteImport } from './routes/launcher-admin.index'
import { Route as LauncherAdminNovosRouteImport } from './routes/launcher-admin.novos'
import { Route as LauncherAdminNovoRouteImport } from './routes/launcher-admin.novo'
import { Route as LauncherAdminLoginRouteImport } from './routes/launcher-admin.login'
import { Route as ApiPublicVerifyLauncherPasswordRouteImport } from './routes/api/public/verify-launcher-password'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiPublicBumpVersionRouteImport } from './routes/api/public/bump-version'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherAdminRoute = LauncherAdminRouteImport.update({
  id: '/launcher-admin',
  path: '/launcher-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherAdminIndexRoute = LauncherAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LauncherAdminRoute,
} as any)
const LauncherAdminNovosRoute = LauncherAdminNovosRouteImport.update({
  id: '/novos',
  path: '/novos',
  getParentRoute: () => LauncherAdminRoute,
} as any)
const LauncherAdminNovoRoute = LauncherAdminNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => LauncherAdminRoute,
} as any)
const LauncherAdminLoginRoute = LauncherAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LauncherAdminRoute,
} as any)
const ApiPublicVerifyLauncherPasswordRoute =
  ApiPublicVerifyLauncherPasswordRouteImport.update({
    id: '/api/public/verify-launcher-password',
    path: '/api/public/verify-launcher-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBumpVersionRoute = ApiPublicBumpVersionRouteImport.update({
  id: '/api/public/bump-version',
  path: '/api/public/bump-version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/launcher-admin': typeof LauncherAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/launcher-admin/login': typeof LauncherAdminLoginRoute
  '/launcher-admin/novo': typeof LauncherAdminNovoRoute
  '/launcher-admin/novos': typeof LauncherAdminNovosRoute
  '/launcher-admin/': typeof LauncherAdminIndexRoute
  '/api/public/bump-version': typeof ApiPublicBumpVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/verify-launcher-password': typeof ApiPublicVerifyLauncherPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/launcher-admin/login': typeof LauncherAdminLoginRoute
  '/launcher-admin/novo': typeof LauncherAdminNovoRoute
  '/launcher-admin/novos': typeof LauncherAdminNovosRoute
  '/launcher-admin': typeof LauncherAdminIndexRoute
  '/api/public/bump-version': typeof ApiPublicBumpVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/verify-launcher-password': typeof ApiPublicVerifyLauncherPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/launcher-admin': typeof LauncherAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/launcher-admin/login': typeof LauncherAdminLoginRoute
  '/launcher-admin/novo': typeof LauncherAdminNovoRoute
  '/launcher-admin/novos': typeof LauncherAdminNovosRoute
  '/launcher-admin/': typeof LauncherAdminIndexRoute
  '/api/public/bump-version': typeof ApiPublicBumpVersionRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/public/verify-launcher-password': typeof ApiPublicVerifyLauncherPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/launcher-admin'
    | '/login'
    | '/launcher-admin/login'
    | '/launcher-admin/novo'
    | '/launcher-admin/novos'
    | '/launcher-admin/'
    | '/api/public/bump-version'
    | '/api/public/catalog'
    | '/api/public/verify-launcher-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/launcher-admin/login'
    | '/launcher-admin/novo'
    | '/launcher-admin/novos'
    | '/launcher-admin'
    | '/api/public/bump-version'
    | '/api/public/catalog'
    | '/api/public/verify-launcher-password'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/launcher-admin'
    | '/login'
    | '/launcher-admin/login'
    | '/launcher-admin/novo'
    | '/launcher-admin/novos'
    | '/launcher-admin/'
    | '/api/public/bump-version'
    | '/api/public/catalog'
    | '/api/public/verify-launcher-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LauncherAdminRoute: typeof LauncherAdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicBumpVersionRoute: typeof ApiPublicBumpVersionRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiPublicVerifyLauncherPasswordRoute: typeof ApiPublicVerifyLauncherPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-admin': {
      id: '/launcher-admin'
      path: '/launcher-admin'
      fullPath: '/launcher-admin'
      preLoaderRoute: typeof LauncherAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-admin/': {
      id: '/launcher-admin/'
      path: '/'
      fullPath: '/launcher-admin/'
      preLoaderRoute: typeof LauncherAdminIndexRouteImport
      parentRoute: typeof LauncherAdminRoute
    }
    '/launcher-admin/novos': {
      id: '/launcher-admin/novos'
      path: '/novos'
      fullPath: '/launcher-admin/novos'
      preLoaderRoute: typeof LauncherAdminNovosRouteImport
      parentRoute: typeof LauncherAdminRoute
    }
    '/launcher-admin/novo': {
      id: '/launcher-admin/novo'
      path: '/novo'
      fullPath: '/launcher-admin/novo'
      preLoaderRoute: typeof LauncherAdminNovoRouteImport
      parentRoute: typeof LauncherAdminRoute
    }
    '/launcher-admin/login': {
      id: '/launcher-admin/login'
      path: '/login'
      fullPath: '/launcher-admin/login'
      preLoaderRoute: typeof LauncherAdminLoginRouteImport
      parentRoute: typeof LauncherAdminRoute
    }
    '/api/public/verify-launcher-password': {
      id: '/api/public/verify-launcher-password'
      path: '/api/public/verify-launcher-password'
      fullPath: '/api/public/verify-launcher-password'
      preLoaderRoute: typeof ApiPublicVerifyLauncherPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bump-version': {
      id: '/api/public/bump-version'
      path: '/api/public/bump-version'
      fullPath: '/api/public/bump-version'
      preLoaderRoute: typeof ApiPublicBumpVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LauncherAdminRouteChildren {
  LauncherAdminLoginRoute: typeof LauncherAdminLoginRoute
  LauncherAdminNovoRoute: typeof LauncherAdminNovoRoute
  LauncherAdminNovosRoute: typeof LauncherAdminNovosRoute
  LauncherAdminIndexRoute: typeof LauncherAdminIndexRoute
}

const LauncherAdminRouteChildren: LauncherAdminRouteChildren = {
  LauncherAdminLoginRoute: LauncherAdminLoginRoute,
  LauncherAdminNovoRoute: LauncherAdminNovoRoute,
  LauncherAdminNovosRoute: LauncherAdminNovosRoute,
  LauncherAdminIndexRoute: LauncherAdminIndexRoute,
}

const LauncherAdminRouteWithChildren = LauncherAdminRoute._addFileChildren(
  LauncherAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LauncherAdminRoute: LauncherAdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicBumpVersionRoute: ApiPublicBumpVersionRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiPublicVerifyLauncherPasswordRoute: ApiPublicVerifyLauncherPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
